# Generated by Django 4.1.7 on 2023-10-03 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Reger',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=50, verbose_name='Имя')),
            ],
            options={
                'verbose_name': 'Register',
                'verbose_name_plural': 'Registration',
            },
        ),
    ]
