# Generated by Django 4.1.7 on 2023-10-06 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reger',
            name='name',
        ),
        migrations.AddField(
            model_name='reger',
            name='password',
            field=models.CharField(default='', max_length=50, verbose_name='Пороль'),
        ),
    ]
