# Generated by Django 4.1.7 on 2023-10-15 18:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_category_alter_photo_options_photo_category'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name': 'Категории', 'verbose_name_plural': 'Категории'},
        ),
    ]
